### ISSUE TITLE
Linux support / compilation issues

### ISSUE THREAD

**Issue by ctreffs** [firebase/abseil-cpp-SwiftPM#1]
Hello Firebase team,

thank you for the SPM port of this great library!

SPM enables it's users to compile for Linux as well as Apple based platforms, 
however I've noticed that compilation for Linux of this project fails currently.
I've not tested this on my machine but rather through the brilliant [Swift Package Index](https://swiftpackageindex.com/) service.

You can see the pipelines and compatibility list for this project here: 
https://swiftpackageindex.com/firebase/abseil-cpp-SwiftPM/builds

Currently `main` does fail to compile on Linux:
https://swiftpackageindex.com/builds/F7A92EE5-F2D8-444F-BC77-3DF3381CCE4E

```
/host/absl/random/internal/randen_hwaes.cc:272:35: error: missing '#include <emmintrin.h>'; declaration of '__m128i' must be imported from module '_Builtin_intrinsics.intel.sse2' before it is required
  inline explicit Vector128(const __m128i& Vector128) : data_(Vector128) {}
                                  ^
/usr/lib/clang/10.0.0/include/emmintrin.h:16:19: note: previous declaration is here
typedef long long __m128i __attribute__((__vector_size__(16), __aligned__(16)));
                  ^
```

I was wondering if it would be hard to fix and if there are at all intensions to support Linux.

Thanks for your time and keep up the good work.

Kind regards,
Chris

**Comment by paulb777** [comment]
Hi @ctreffs - Thanks for the kind words and feature request.

Sorry, but the Firebase team has no plans to support Swift Package Manager and Linux.  It might make sense to reach out directly to the abseil project to make the request - perhaps at https://github.com/abseil/abseil-cpp/issues
